import { makeStyles } from "tss-react/mui";

const useHomeStyles = makeStyles()((theme) => ({
  heroSection: {
    background:
      "linear-gradient(135deg, #F7FAFC 0%, #EDF2F7 50%, #E2E8F0 100%)",
    paddingTop: theme.spacing(10),
    paddingBottom: theme.spacing(15),
    position: "relative",
    overflow: "hidden",
    minHeight: "100vh",
    display: "flex",
    alignItems: "center",
    [theme.breakpoints.down("md")]: {
      paddingTop: theme.spacing(8),
      paddingBottom: theme.spacing(12),
    },
  },
  decorativeElement1: {
    position: "absolute",
    top: "10%",
    right: "10%",
    width: "300px",
    height: "300px",
    background:
      "linear-gradient(135deg, rgba(108, 92, 231, 0.1), rgba(202, 8, 88, 0.1))",
    borderRadius: "50%",
    filter: "blur(60px)",
    zIndex: 1,
  },
  decorativeElement2: {
    position: "absolute",
    bottom: "20%",
    left: "5%",
    width: "200px",
    height: "200px",
    background:
      "linear-gradient(135deg, rgba(45, 55, 72, 0.1), rgba(108, 92, 231, 0.1))",
    borderRadius: "50%",
    filter: "blur(40px)",
    zIndex: 1,
  },
  heroTitle: {
    fontSize: "3.5rem",
    fontWeight: 800,
    marginBottom: theme.spacing(3),
    background:
      "linear-gradient(135deg, #2D3748 0%, #4A5568 50%, #CA0858 100%)",
    backgroundClip: "text",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
    lineHeight: 1.1,
    [theme.breakpoints.down("md")]: {
      fontSize: "3rem",
    },
  },
  heroSubtitle: {
    marginBottom: theme.spacing(4),
    fontWeight: 400,
    fontSize: "2.2rem",
    color: "#2D3748",
    lineHeight: 1.3,
    [theme.breakpoints.down("md")]: {
      fontSize: "1.5rem",
    },
  },
  highlightChip: {
    background: "rgba(255, 255, 255, 0.95)",
    color: "#2D3748",
    fontWeight: 600,
    fontSize: "0.9rem",
    padding: theme.spacing(2.5, 1),
    border: "1px solid rgba(45, 55, 72, 0.2)",
    backdropFilter: "blur(10px)",
    boxShadow: "0 4px 20px rgba(45, 55, 72, 0.1)",
    transition: "all 0.3s ease",
  },
  primaryButton: {
    padding: theme.spacing(1.5, 4),
    fontSize: "1.2rem",
    fontWeight: 700,
    borderRadius: 20,
    background: "linear-gradient(135deg, #CA0858 0%, #E91E63 100%)",
    boxShadow: "0 8px 30px rgba(202, 8, 88, 0.3)",
    transition: "all 0.3s ease",
    "&:hover": {
      transform: "translateY(-3px)",
      boxShadow: "0 15px 40px rgba(202, 8, 88, 0.4)",
      background: "linear-gradient(135deg, #8E0038 0%, #CA0858 100%)",
    },
  },
  secondaryButton: {
    padding: theme.spacing(1.5, 4),
    fontSize: "1.1rem",
    fontWeight: 600,
    borderRadius: 20,
    borderWidth: 2,
    background: "rgba(255, 255, 255, 0.95)",
    backdropFilter: "blur(10px)",
    borderColor: "#2D3748",
    color: "#2D3748",
    transition: "all 0.3s ease",
    "&:hover": {
      borderWidth: 2,
      transform: "translateY(-2px)",
      borderColor: "#2D3748",
      backgroundColor: "unset",
      color: "#2D3748",
      boxShadow: "none",
    },
  },
  avatarContainer: {
    width: "500px",
    height: "500px",
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    [theme.breakpoints.down("md")]: {
      width: "350px",
      height: "350px",
    },
  },
  gallerySection: {
    background:
      "linear-gradient(135deg, rgba(255, 240, 245, 0.5) 0%, rgba(248, 250, 252, 0.8) 100%)",
    padding: "30px 0px",
    position: "relative",
    "&:before": {
      content: '""',
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundImage:
        "radial-gradient(circle at 20% 80%, rgba(202, 8, 88, 0.08) 0%, transparent 50%), radial-gradient(circle at 80% 20%, rgba(108, 92, 231, 0.08) 0%, transparent 50%)",
    },
    [theme.breakpoints.down("md")]: {
      padding: "20px 0px",
    },
  },
  galleryImageAnimation: {
    borderRadius: 5,
    overflow: "hidden",
    height: 280,
    backgroundSize: "cover",
    backgroundPosition: "center",
    transition: "all 0.8s ease-in-out",
    cursor: "pointer",
    position: "relative",

    "&:after": {
      content: '""',
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      background: "linear-gradient(45deg, rgba(202, 8, 88, 0.1), transparent)",
      opacity: 0,
      transition: "opacity 0.3s ease",
    },
  },
  heroDescription: {
    marginBottom: "30px",
    fontSize: "18px",
    lineHeight: 1.7,
    maxWidth: "600px",
    color: "#4A5568",
    fontWeight: 400,
  },
  avatarImage: {
    width: "98%",
    height: "98%",
    borderTopLeftRadius: "50%",
    borderTopRightRadius: "50%",
    borderBottomRightRadius: "50%",
    objectFit: "contain",
    boxShadow: "0 5px 100px rgba(253, 59, 124, 0.3)",
    backgroundColor: "rgba(244, 187, 206, 0.3)",
  },
}));

export default useHomeStyles;
